/**** BEGIN COPYRIGHT ********************************************************
 *
 * Copyright (C) 2007 - 2012, Rogvall Invest AB, <tony@rogvall.se>
 *
 * This software is licensed as described in the file COPYRIGHT, which
 * you should have received as part of this distribution. The terms
 * are also available at http://www.rogvall.se/docs/copyright.txt.
 *
 * You may opt to use, copy, modify, merge, publish, distribute and/or sell
 * copies of the Software, and permit persons to whom the Software is
 * furnished to do so, under the terms of the COPYRIGHT file.
 *
 * This software is distributed on an "AS IS" basis, WITHOUT WARRANTY OF ANY
 * KIND, either express or implied.
 *
 **** END COPYRIGHT **********************************************************/
// Generated by eapi (DO NOT EDIT)
#include "eapi_drv.h"
#include "sl_drv.h"

int eapi_dispatch(eapi_ctx_t* ctx, unsigned int cmd, cbuf_t* c_in, cbuf_t* c_out)
{
  switch(cmd) {
  case SL_DRV_CMD_OPEN: {
    sl_drv_impl_open(ctx,c_out);
    break;
  }
  case SL_DRV_CMD_CONNECT: {
    sl_drv_impl_connect(ctx,c_out);
    break;
  }
  case SL_DRV_CMD_DISCONNECT: {
    sl_drv_impl_disconnect(ctx,c_out);
    break;
  }
  case SL_DRV_CMD_CLOSE: {
    sl_drv_impl_close(ctx,c_out);
    break;
  }
  case SL_DRV_CMD_XON: {
    sl_drv_impl_xon(ctx,c_out);
    break;
  }
  case SL_DRV_CMD_XOFF: {
    sl_drv_impl_xoff(ctx,c_out);
    break;
  }
  case SL_DRV_CMD_BREAK: {
    sl_drv_impl_break(ctx,c_out);
    break;
  }
  case SL_DRV_CMD_UPDATE: {
    sl_drv_impl_update(ctx,c_out);
    break;
  }
  case SL_DRV_CMD_REVERT: {
    sl_drv_impl_revert(ctx,c_out);
    break;
  }
  case SL_DRV_CMD_SENDCHAR: {
    uint8_t c;
    cbuf_get_uint8(c_in,&c);
    sl_drv_impl_sendchar(ctx,c_out,c);
    break;
  }
  case SL_DRV_CMD_SEND: {
    eapi_binary_t data;
    cbuf_get_nbinary(c_in,&data);
    sl_drv_impl_send(ctx,c_out,&data);
    cbuf_free_binary(&(data));
    break;
  }
  case SL_DRV_CMD_GET_BAUD_RATES: {
    sl_drv_impl_get_baud_rates(ctx,c_out);
    break;
  }
  case SL_DRV_CMD_SET_DEVICE: {
    eapi_string_t name;
    cbuf_get_nstring(c_in,&name);
    sl_drv_impl_set_device(ctx,c_out,&name);
    cbuf_free_string(&(name));
    break;
  }
  case SL_DRV_CMD_SET_IBAUD: {
    int32_t baud;
    cbuf_get_int32(c_in,&baud);
    sl_drv_impl_set_ibaud(ctx,c_out,baud);
    break;
  }
  case SL_DRV_CMD_SET_OBAUD: {
    int32_t baud;
    cbuf_get_int32(c_in,&baud);
    sl_drv_impl_set_obaud(ctx,c_out,baud);
    break;
  }
  case SL_DRV_CMD_SET_CSIZE: {
    int32_t csize;
    cbuf_get_int32(c_in,&csize);
    sl_drv_impl_set_csize(ctx,c_out,csize);
    break;
  }
  case SL_DRV_CMD_SET_BUFSIZE: {
    int32_t bufsize;
    cbuf_get_int32(c_in,&bufsize);
    sl_drv_impl_set_bufsize(ctx,c_out,bufsize);
    break;
  }
  case SL_DRV_CMD_SET_BUFTM: {
    int32_t buftm;
    cbuf_get_int32(c_in,&buftm);
    sl_drv_impl_set_buftm(ctx,c_out,buftm);
    break;
  }
  case SL_DRV_CMD_SET_STOPB: {
    int32_t stopb;
    cbuf_get_int32(c_in,&stopb);
    sl_drv_impl_set_stopb(ctx,c_out,stopb);
    break;
  }
  case SL_DRV_CMD_SET_PARITY: {
    int32_t parity;
    cbuf_get_int32(c_in,&parity);
    sl_drv_impl_set_parity(ctx,c_out,parity);
    break;
  }
  case SL_DRV_CMD_SET_HWFLOW: {
    uint8_t enable;
    cbuf_get_boolean(c_in,&enable);
    sl_drv_impl_set_hwflow(ctx,c_out,enable);
    break;
  }
  case SL_DRV_CMD_SET_SWFLOW: {
    uint8_t enable;
    cbuf_get_boolean(c_in,&enable);
    sl_drv_impl_set_swflow(ctx,c_out,enable);
    break;
  }
  case SL_DRV_CMD_SET_XOFFCHAR: {
    int32_t c;
    cbuf_get_int32(c_in,&c);
    sl_drv_impl_set_xoffchar(ctx,c_out,c);
    break;
  }
  case SL_DRV_CMD_SET_XONCHAR: {
    int32_t c;
    cbuf_get_int32(c_in,&c);
    sl_drv_impl_set_xonchar(ctx,c_out,c);
    break;
  }
  case SL_DRV_CMD_SET_EOLCHAR: {
    int32_t c;
    cbuf_get_int32(c_in,&c);
    sl_drv_impl_set_eolchar(ctx,c_out,c);
    break;
  }
  case SL_DRV_CMD_SET_EOL2CHAR: {
    int32_t c;
    cbuf_get_int32(c_in,&c);
    sl_drv_impl_set_eol2char(ctx,c_out,c);
    break;
  }
  case SL_DRV_CMD_SET_MODE: {
    int32_t mode;
    cbuf_get_int32(c_in,&mode);
    sl_drv_impl_set_mode(ctx,c_out,mode);
    break;
  }
  case SL_DRV_CMD_GET_DEVICE: {
    sl_drv_impl_get_device(ctx,c_out);
    break;
  }
  case SL_DRV_CMD_GET_IBAUD: {
    sl_drv_impl_get_ibaud(ctx,c_out);
    break;
  }
  case SL_DRV_CMD_GET_OBAUD: {
    sl_drv_impl_get_obaud(ctx,c_out);
    break;
  }
  case SL_DRV_CMD_GET_CSIZE: {
    sl_drv_impl_get_csize(ctx,c_out);
    break;
  }
  case SL_DRV_CMD_GET_BUFSIZE: {
    sl_drv_impl_get_bufsize(ctx,c_out);
    break;
  }
  case SL_DRV_CMD_GET_BUFTM: {
    sl_drv_impl_get_buftm(ctx,c_out);
    break;
  }
  case SL_DRV_CMD_GET_STOPB: {
    sl_drv_impl_get_stopb(ctx,c_out);
    break;
  }
  case SL_DRV_CMD_GET_PARITY: {
    sl_drv_impl_get_parity(ctx,c_out);
    break;
  }
  case SL_DRV_CMD_GET_HWFLOW: {
    sl_drv_impl_get_hwflow(ctx,c_out);
    break;
  }
  case SL_DRV_CMD_GET_SWFLOW: {
    sl_drv_impl_get_swflow(ctx,c_out);
    break;
  }
  case SL_DRV_CMD_GET_XOFFCHAR: {
    sl_drv_impl_get_xoffchar(ctx,c_out);
    break;
  }
  case SL_DRV_CMD_GET_XONCHAR: {
    sl_drv_impl_get_xonchar(ctx,c_out);
    break;
  }
  case SL_DRV_CMD_GET_EOLCHAR: {
    sl_drv_impl_get_eolchar(ctx,c_out);
    break;
  }
  case SL_DRV_CMD_GET_EOL2CHAR: {
    sl_drv_impl_get_eol2char(ctx,c_out);
    break;
  }
  case SL_DRV_CMD_GET_MODE: {
    sl_drv_impl_get_mode(ctx,c_out);
    break;
  }
  default:
    return -1;
  }
  return 0;
}
