%%%---- BEGIN COPYRIGHT --------------------------------------------------------
%%%
%%% Copyright (C) 2007 - 2012, Rogvall Invest AB, <tony@rogvall.se>
%%%
%%% This software is licensed as described in the file COPYRIGHT, which
%%% you should have received as part of this distribution. The terms
%%% are also available at http://www.rogvall.se/docs/copyright.txt.
%%%
%%% You may opt to use, copy, modify, merge, publish, distribute and/or sell
%%% copies of the Software, and permit persons to whom the Software is
%%% furnished to do so, under the terms of the COPYRIGHT file.
%%%
%%% This software is distributed on an "AS IS" basis, WITHOUT WARRANTY OF ANY
%%% KIND, either express or implied.
%%%
%%%---- END COPYRIGHT ----------------------------------------------------------
%% Generated by eapi (DO NOT EDIT)
-ifndef(__SL_DRV_HRL__).
-define(__SL_DRV_HRL__,true).
-define(SL_CMD_OPEN,1).
-define(SL_CMD_CONNECT,2).
-define(SL_CMD_DISCONNECT,3).
-define(SL_CMD_CLOSE,4).
-define(SL_CMD_XON,5).
-define(SL_CMD_XOFF,6).
-define(SL_CMD_BREAK,7).
-define(SL_CMD_UPDATE,8).
-define(SL_CMD_REVERT,9).
-define(SL_CMD_SENDCHAR,10).
-define(SL_CMD_SEND,11).
-define(SL_CMD_GET_BAUD_RATES,12).
-define(SL_CMD_SET_DEVICE,13).
-define(SL_CMD_SET_IBAUD,14).
-define(SL_CMD_SET_OBAUD,15).
-define(SL_CMD_SET_CSIZE,16).
-define(SL_CMD_SET_BUFSIZE,17).
-define(SL_CMD_SET_BUFTM,18).
-define(SL_CMD_SET_STOPB,19).
-define(SL_CMD_SET_PARITY,20).
-define(SL_CMD_SET_HWFLOW,21).
-define(SL_CMD_SET_SWFLOW,22).
-define(SL_CMD_SET_XOFFCHAR,23).
-define(SL_CMD_SET_XONCHAR,24).
-define(SL_CMD_SET_EOLCHAR,25).
-define(SL_CMD_SET_EOL2CHAR,26).
-define(SL_CMD_SET_MODE,27).
-define(SL_CMD_GET_DEVICE,28).
-define(SL_CMD_GET_IBAUD,29).
-define(SL_CMD_GET_OBAUD,30).
-define(SL_CMD_GET_CSIZE,31).
-define(SL_CMD_GET_BUFSIZE,32).
-define(SL_CMD_GET_BUFTM,33).
-define(SL_CMD_GET_STOPB,34).
-define(SL_CMD_GET_PARITY,35).
-define(SL_CMD_GET_HWFLOW,36).
-define(SL_CMD_GET_SWFLOW,37).
-define(SL_CMD_GET_XOFFCHAR,38).
-define(SL_CMD_GET_XONCHAR,39).
-define(SL_CMD_GET_EOLCHAR,40).
-define(SL_CMD_GET_EOL2CHAR,41).
-define(SL_CMD_GET_MODE,42).
-endif.
